apiVersion: v1
kind: PersistentVolume
metadata:
  name: nats-data-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/nats"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nats-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi